services:
  rails:
    build:
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: devpassword

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: devpassword
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

volumes:
  dev-db-data:
